## SSE

As input, we will receive a list of cluster along with the points that belong to them, i.e.:
- input=[cluster1, cluster2, cluster3 ...]
- clusterN=[x1,x2,x3...]

In [72]:
import numpy as np

In [73]:
# Initializing List of Clusters
oned_cluster = [np.random.uniform(low=1.0, high=10.0, size=20)
for i in range(10)
]
oned_cluster

[array([3.9186019 , 6.67964378, 3.95430431, 1.90117822, 8.10139771,
        8.30432089, 2.09575177, 4.076664  , 8.28032896, 5.30120602,
        7.7266808 , 2.43775942, 4.30270609, 3.03237187, 3.37147159,
        6.82706421, 6.85755848, 2.77975737, 6.68245222, 9.97821867]),
 array([6.98238459, 7.40687816, 6.75138427, 9.44319861, 5.31727027,
        7.56130505, 8.72551368, 9.85423828, 8.15580011, 6.56667648,
        9.70595421, 6.74019898, 7.95873441, 4.44846259, 4.50411116,
        2.27363826, 1.08725183, 8.14591459, 1.63933378, 2.63084416]),
 array([5.04742735, 4.9493005 , 6.11960431, 7.68660888, 4.11312136,
        7.84925482, 6.93328367, 8.50513242, 2.51316375, 9.48610343,
        7.74022175, 2.58404031, 8.86538348, 7.34568524, 9.65134973,
        8.04602758, 8.39883868, 4.29261098, 1.49707397, 6.68501853]),
 array([9.41529952, 6.82268748, 9.26526782, 7.79589566, 9.26932971,
        5.79870924, 4.55514512, 9.18643169, 9.63747535, 8.37119824,
        8.15412486, 5.02817993, 7.42572385

In [74]:
# Compute SSE
def sse_1d(clusters):
    sse=list()
    for c in clusters:
        mu=np.mean(c)
        sse.extend([(ci-mu)**2 for ci in c])
    return np.sum(sse)

In [75]:
sse_1d(oned_cluster)

1240.9192560667134

In [76]:
second_clusters = [np.random.uniform(low=1.0, high=10.0, size=20)
for y in range(10)
]
twod_clusters = list(zip(oned_cluster, second_clusters))
twod_clusters[0]

(array([3.9186019 , 6.67964378, 3.95430431, 1.90117822, 8.10139771,
        8.30432089, 2.09575177, 4.076664  , 8.28032896, 5.30120602,
        7.7266808 , 2.43775942, 4.30270609, 3.03237187, 3.37147159,
        6.82706421, 6.85755848, 2.77975737, 6.68245222, 9.97821867]),
 array([2.71764   , 7.09356586, 3.1767905 , 5.26744994, 5.98358111,
        7.0476466 , 8.58868402, 1.03015033, 5.28638262, 1.97681592,
        9.42204894, 5.83158833, 9.42042533, 2.66745158, 3.1994754 ,
        7.40904851, 8.95862522, 8.41956457, 3.51418417, 9.36500441]))

In [78]:
# Pair-wise squared distances
def sse_2d(clusters):
    sse_x = list()
    sse_y = list()

    for x, y in clusters:
        mu_x = np.mean(x)
        mu_y = np.mean(y)
        for ci in x:
            sse_x.extend([(ci-mu_x)**2])
        for cj in y:
            sse_y.extend([(cj-mu_y)**2])
    sum_x = np.sum(sse_x)
    sum_y = np.sum(sse_y)    
    return [sum_x, sum_y]
        

sse_2d(twod_clusters)

[1240.9192560667134, 1287.6984880450484]

## Davies-Bouldin Index

Implement the DB-Index


In [79]:
# DB Index: DB(C)
def db_index(clusters):
    dbi=0
    for i, ic in enumerate(clusters):
        Dij_val = []
        for k, kc in enumerate(clusters):
            Dij_val.append(Dij(ic,kc))
        dbi_sum += max(Dij_val)

In [80]:
# within-to-between cluster distance
def d_ij(ci, cj):
    mu_i = np.mean(ci)
    mu_j = np.mean(cj)
    return abs(mu_i - mu_j)

### Average distance between each point in a cluster

In [81]:
# within-to-between cluster distance
def d_bar(ci):
    centroud = np.mean(ci)
    dist = []
    for pt in ci:
        dist.append(abs(pt-centroud))  # absolute distance from centroid eg. pt=1, dist=abs(1-5)=4
    return np.mean(dist)

In [82]:
def Dij(ci, cj):
    return ((d_bar(ci) + d_bar(cj))/d_ij(ci, cj))